In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
import joblib

In [64]:
train_df = pd.read_csv("../data/train.csv", index_col="ID")
clients_df = pd.read_csv("../data/clientes.csv", index_col="customer_id")
test_df = pd.read_csv("../data/test.csv")

In [65]:
clients_df.head()

,country_or_region,commercial_region,island,municipality,city,postal_area,postal_code,street,address,customer_type,company_name,customer_since_year
customer_id,,,,,,,,,,,,
842570,Country CT11: Land of The Final Version,Region RG37: We Will See Later,NaN,NaN,City CY417: Missing Cell Port,NaN,Postal code PC828: #REF! Delivery Route,NaN,Address AD1120: Cell Without a Home,NaN,Excel Is Not A Database Ltd 150,2018
770941,Country CT9: Land of The Final Version,NaN,NaN,NaN,NaN,NaN,Postal code PC56: #REF! Delivery Route,NaN,Address AD62: Cell Without a Home,NaN,Excel Is Not A Database Ltd 1064,2021
827053,Country CT10: Land of The Final Version,Region RG17: We Will See Later,Island IS2: The Pivot Archipelago,Municipality MU14: Council of Last Minute Edits,NaN,Postal area PA271: Hidden Sheet Sector,Postal code PC827: #REF! Delivery Route,Street ST170: PowerPoint New Walk,Address AD449: Cell Without a Home,NaN,Excel Is Not A Database Ltd 113,2016
494648,Country CT10: Land of The Final Version,Region RG17: We Will See Later,Island IS2: The Pivot Archipelago,Municipality MU14: Council of Last Minute Edits,NaN,Postal area PA271: Hidden Sheet Sector,Postal code PC826: #REF! Delivery Route,NaN,Address AD454: Cell Without a Home,NaN,Excel Is Not A Database Ltd 430,2015
429291,Country CT10: Land of The Final Version,Region RG17: We Will See Later,Island IS2: The Pivot Archipelago,Municipality MU14: Council of Last Minute Edits,NaN,Postal area PA271: Hidden Sheet Sector,Postal code PC826: #REF! Delivery Route,NaN,Address AD453: Cell Without a Home,NaN,Excel Is Not A Database Ltd 673,2015

In [6]:
train_df.head()

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,...,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,random_noise
ID,,,,,,,,,,,,,,,,,,,,,
10000000,558.11,510.90,453.75,104.36,0.0,0.0,57.15,153.099911,4.0,1.0,...,858.30,660784,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,-0.660448
10000001,978.80,830.02,795.77,183.03,0.0,0.0,34.25,472.943134,32.0,1.0,...,2500.68,189146,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,0.924510
10000002,10.33,12.00,8.40,1.93,0.0,0.0,3.60,6.097485,1.0,1.0,...,7899.80,103940,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,-0.258730
10000003,856.83,696.61,696.61,160.22,0.0,0.0,0.00,408.167275,9.0,1.0,...,270.33,512927,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 71,Final Excel Warehouse 1,Ctrl Z Series 3,2018-11-10,1.448402
10000004,1616.10,1488.85,1313.90,302.20,0.0,0.0,174.95,485.401864,33.0,1.0,...,2062.50,122356,Maybe Tomorrow Payment 12,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2021-11-30,-1.058890

In [67]:
clients_df.shape

(1143, 12)

In [41]:
train_df.shape

(6534, 38)

In [68]:
clients_df.info()

<class 'pandas.DataFrame'>
Index: 1143 entries, 842570 to 312616
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country_or_region    1143 non-null   str
 1   commercial_region    1029 non-null   str
 2   island               565 non-null    str
 3   municipality         984 non-null    str
 4   city                 597 non-null    str
 5   postal_area          1072 non-null   str
 6   postal_code          973 non-null    str
 7   street               545 non-null    str
 8   address              1137 non-null   str
 9   customer_type        0 non-null      float64
 10  company_name         1143 non-null   str
 11  customer_since_year  1143 non-null   int64
dtypes: float64(1), int64(1), str(10)
memory usage: 116.1 KB

In [23]:
train_df.info()

<class 'pandas.DataFrame'>
Index: 6534 entries, 10000000 to 10007674
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6534 non-null   int64
 11  days_since_previous_purchase    5673 non-null   float64
 12  customer_tenure_days            6469 non-null   float64
 13  prior_purchase_count            6469 non-null   float64
 14  prior_total_spend               6469 non-null   float64
 15  prior_mean_purchase_value       5672 non-null   float64
 16  prior_std_purchase_value        5421 non-null   float64
 17  prior_min_purchase_value        5866 non-null   float64
 18  prior_max_purchase_value        5866 non-null   float64
 19  prior_mean_gap_days             5226 non-null   float64
 20  prior_std_gap_days              5056 non-null   float64
 21  purchase_count_30d              6469 non-null   float64
 22  spend_30d                       6469 non-null   float64
 23  purchase_count_90d              6469 non-null   float64
 24  spend_90d                       6469 non-null   float64
 25  purchase_count_180d             6469 non-null   float64
 26  spend_180d                      6469 non-null   float64
 27  purchase_count_365d             6469 non-null   float64
 28  spend_365d                      6274 non-null   float64
 29  customer_id                     6534 non-null   int64
 30  payment_type                    6274 non-null   str
 31  salesperson                     6275 non-null   str
 32  commercial_zone                 6469 non-null   str
 33  transport_method                6273 non-null   str
 34  warehouse                       6274 non-null   str
 35  document_series                 6469 non-null   str
 36  purchase_date                   6469 non-null   str
 37  random_noise                    6469 non-null   float64
dtypes: float64(29), int64(2), str(7)
memory usage: 1.9 MB

In [ ]:
train_df[train_df.duplicated()].T

ID,10000560,10003209,10003718,10004463,10005141,10005177,10005269,10005608,10006618,10007583
Total a Pagar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Bruto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Liquido,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Imp_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Portes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Desc_ Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Desc_ Linha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Custo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N_ Detalhes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
invoice_count_current_purchase,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
repeat_purchase_90d,1,1,1,1,1,0,1,1,1,0
days_since_previous_purchase,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_tenure_days,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_purchase_count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_total_spend,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_mean_purchase_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_std_purchase_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_min_purchase_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_max_purchase_value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_mean_gap_days,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_std_gap_days,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_count_30d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spend_30d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_count_90d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spend_90d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_count_180d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spend_180d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_count_365d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spend_365d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,755628,755628,334782,755628,239651,928824,258332,755628,258332,264090
payment_type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salesperson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
commercial_zone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transport_method,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warehouse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
document_series,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
random_noise,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
#Como são linhas totalmente vazias (à exceção das colunas customer id e da target) acho que as podemos remover do dataframe
#Retirei estas duas colunas porque são as únicas que não têm nenhum missing value e linhas só com esses dois valores são desnecessárias
drop_customer_df = train_df.drop(columns=["customer_id", "repeat_purchase_90d"])
all_missing = drop_customer_df.isna().all(axis=1)
train_df[all_missing]

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,...,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,random_noise
ID,,,,,,,,,,,,,,,,,,,,,
10000457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,755628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,755628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,427118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,508217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,427118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10007151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,151492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,230585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,902830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,264090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,697676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
train_df.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
Total a Pagar,6469.0,925.56,1335.00,0.93,188.92,476.74,1087.67,2.229721e+04
Total Bruto,6469.0,886.15,1327.64,0.83,175.74,445.74,1036.70,2.157828e+04
Total Liquido,6469.0,773.34,1136.36,0.76,154.38,389.91,903.37,1.812781e+04
Total Imp_,6469.0,152.22,225.26,0.00,29.93,79.74,184.84,4.169400e+03
Total Portes,6469.0,1.15,5.84,0.00,0.00,0.00,0.00,1.810600e+02
Total Desc_ Global,6469.0,0.35,5.12,0.00,0.00,0.00,0.00,2.184900e+02
Total Desc_ Linha,6469.0,112.47,289.99,0.00,0.00,13.13,92.28,4.103440e+03
Custo,6469.0,328.17,519.51,0.00,49.05,152.54,396.06,7.427400e+03
N_ Detalhes,6469.0,21.52,27.71,1.00,4.00,11.00,29.00,4.230000e+02
invoice_count_current_purchase,6469.0,1.07,0.31,1.00,1.00,1.00,1.00,5.000000e+00
repeat_purchase_90d,6534.0,0.56,0.50,0.00,0.00,1.00,1.00,1.000000e+00
days_since_previous_purchase,5673.0,101.53,165.70,-4.00,17.00,57.00,119.00,3.199000e+03
customer_tenure_days,6469.0,1111.38,923.19,0.00,308.00,918.00,1759.00,3.506000e+03
prior_purchase_count,6469.0,23.46,38.34,0.00,3.00,11.00,27.00,2.760000e+02
prior_total_spend,6469.0,18908.35,31130.87,0.00,1505.55,6754.31,21642.32,2.478651e+05
prior_mean_purchase_value,5672.0,2821825.32,53041566.66,-2478.66,359.56,724.90,1095.89,1.000000e+09
prior_std_purchase_value,5421.0,737.47,666.26,0.00,258.56,569.08,981.09,6.770220e+03
prior_min_purchase_value,5866.0,185.46,408.40,0.93,15.45,64.34,162.61,6.298980e+03
prior_max_purchase_value,5866.0,2946.38,5901.55,3.31,834.53,1783.24,3504.42,2.675262e+05
prior_mean_gap_days,5226.0,95.88,122.59,-4.00,42.60,68.44,113.83,3.199000e+03
prior_std_gap_days,5056.0,74.14,101.82,0.00,32.74,50.64,78.63,2.212540e+03
purchase_count_30d,6469.0,0.60,1.21,0.00,0.00,0.00,1.00,1.100000e+01
spend_30d,6469.0,457.14,1191.23,0.00,0.00,0.00,338.24,2.229721e+04
purchase_count_90d,6469.0,1.63,2.98,0.00,0.00,1.00,2.00,2.200000e+01
spend_90d,6469.0,1253.53,2347.84,0.00,0.00,198.50,1514.56,3.023488e+04
purchase_count_180d,6469.0,3.37,5.46,0.00,1.00,2.00,3.00,3.700000e+01
spend_180d,6469.0,2650.60,4020.27,0.00,149.16,1117.68,3404.44,4.974697e+04
purchase_count_365d,6469.0,6.56,10.33,0.00,1.00,3.00,7.00,6.000000e+01
spend_365d,6274.0,2396534.88,48841133.46,-159115.18,637.78,2426.60,7045.42,1.000000e+09
customer_id,6534.0,506471.91,266556.04,103940.00,258332.00,489625.00,755628.00,9.988700e+05
random_noise,6469.0,-0.02,1.00,-3.53,-0.68,-0.05,0.64,4.150000e+00

In [70]:
clients_df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_since_year,1143.0,2016.999125,2.971405,2015.0,2015.0,2015.0,2018.0,2026.0

In [27]:
train_df.describe(include="object").T

/var/folders/95/1xf01h296vjbznnd0l4gq4300000gn/T/ipykernel_17246/301154582.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  train_df.describe(include="object").T

                 count unique                          top  freq
payment_type      6274      9     Maybe Tomorrow Payment 7  4565
salesperson       6275      9             VLOOKUP Master 1  4054
commercial_zone   6469      5  Decorative Dashboard Zone 4  6260
transport_method  6273     80   Maybe Tomorrow Delivery 72  1119
warehouse         6274      2      Final Excel Warehouse 1  6253
document_series   6469      3              Ctrl Z Series 2  2738
purchase_date     6469   1492                   2015-10-31    52

In [40]:
print(f"Unique payment types: {train_df["payment_type"].unique()}")
print(f"Unique Sales Person: {train_df["salesperson"].unique()}")
print(f"Unique Commercial Zone: {train_df["commercial_zone"].unique()}")
print(f"Unique Warehouse: {train_df["warehouse"].unique()}")
print(f"Unique Document Series: {train_df["document_series"].unique()}")

Unique payment types: <StringArray>
['Maybe Tomorrow Payment 10',  'Maybe Tomorrow Payment 7',
  'Maybe Tomorrow Payment 9', 'Maybe Tomorrow Payment 12',
                         nan,  'Maybe Tomorrow Payment 2',
  'Maybe Tomorrow Payment 8',  'Maybe Tomorrow Payment 3',
  'Maybe Tomorrow Payment 4', 'Maybe Tomorrow Payment 11']
Length: 10, dtype: str
Unique Sales Person: <StringArray>
['VLOOKUP Master 9', 'VLOOKUP Master 1', 'VLOOKUP Master 4',
                nan, 'VLOOKUP Master 2', 'VLOOKUP Master 7',
 'VLOOKUP Master 6', 'VLOOKUP Master 3', 'VLOOKUP Master 5',
 'VLOOKUP Master 8']
Length: 10, dtype: str
Unique Commercial Zone: <StringArray>
['Decorative Dashboard Zone 4', 'Decorative Dashboard Zone 2',
 'Decorative Dashboard Zone 3',                           nan,
 'Decorative Dashboard Zone 6', 'Decorative Dashboard Zone 7']
Length: 6, dtype: str
Unique Warehouse: <StringArray>
['Final Excel Warehouse 1', 'Final Excel Warehouse 3', nan]
Length: 3, dtype: str
Unique Document Series: <StringArray>
['Ctrl Z Series 2', 'Ctrl Z Series 1', 'Ctrl Z Series 3', nan]
Length: 4, dtype: str

In [71]:
clients_df.describe(include="object").T

/var/folders/95/1xf01h296vjbznnd0l4gq4300000gn/T/ipykernel_17246/945293564.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  clients_df.describe(include="object").T

,count,unique,top,freq
country_or_region,1143,11,Country CT10: Land of The Final Version,1079
commercial_region,1029,37,Region RG17: We Will See Later,519
island,565,10,Island IS7: The Pivot Archipelago,133
municipality,984,183,Municipality MU1: Council of Last Minute Edits,58
city,597,417,City CY194: PowerPoint New Hills,14
postal_area,1072,271,Postal area PA259: Hidden Sheet Sector,57
postal_code,973,828,Postal code PC545: #REF! Delivery Route,6
street,545,511,Street ST192: Last Save Walk,5
address,1137,1120,Address AD489: Cell Without a Home,3
company_name,1143,1141,Excel Is Not A Database Ltd 384,2

In [29]:
train_df["repeat_purchase_90d"].value_counts()

repeat_purchase_90d
1    3654
0    2880
Name: count, dtype: int64

In [34]:
train_df.groupby("repeat_purchase_90d").mean(numeric_only=True).round(2).T

repeat_purchase_90d                      0           1
Total a Pagar                       808.56     1017.58
Total Bruto                         762.81      983.17
Total Liquido                       680.06      846.70
Total Imp_                          128.49      170.88
Total Portes                          1.16        1.15
Total Desc_ Global                    0.42        0.30
Total Desc_ Linha                    82.33      136.17
Custo                               299.83      350.45
N_ Detalhes                          20.79       22.10
invoice_count_current_purchase        1.05        1.08
days_since_previous_purchase        139.88       74.16
customer_tenure_days               1000.70     1198.44
prior_purchase_count                 10.54       33.62
prior_total_spend                  9714.56    26139.47
prior_mean_purchase_value       2537890.96  3024880.89
prior_std_purchase_value            628.06      810.33
prior_min_purchase_value            233.24      151.29
prior_max_purchase_value           2249.21     3445.00
prior_mean_gap_days                 131.47       71.96
prior_std_gap_days                  100.43       57.65
purchase_count_30d                    0.24        0.88
spend_30d                           235.29      631.63
purchase_count_90d                    0.53        2.50
spend_90d                           541.73     1813.37
purchase_count_180d                   1.32        4.99
spend_180d                         1286.17     3723.75
purchase_count_365d                   2.60        9.68
spend_365d                      1812450.99  2856182.77
customer_id                      540098.49   479968.21
random_noise                         -0.01       -0.03

In [44]:
train_df[train_df["customer_id"] == "Null"]

Empty DataFrame
Columns: [Total a Pagar, Total Bruto, Total Liquido, Total Imp_, Total Portes, Total Desc_ Global, Total Desc_ Linha, Custo, N_ Detalhes, invoice_count_current_purchase, repeat_purchase_90d, days_since_previous_purchase, customer_tenure_days, prior_purchase_count, prior_total_spend, prior_mean_purchase_value, prior_std_purchase_value, prior_min_purchase_value, prior_max_purchase_value, prior_mean_gap_days, prior_std_gap_days, purchase_count_30d, spend_30d, purchase_count_90d, spend_90d, purchase_count_180d, spend_180d, purchase_count_365d, spend_365d, customer_id, payment_type, salesperson, commercial_zone, transport_method, warehouse, document_series, purchase_date, random_noise]
Index: []

[0 rows x 38 columns]